version: '3.3'

services: 
    mongo:
      image: mongo
      environment: 
        MONGO_INITDB_DATABASE: fav
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: 123
      ports: 
        - "27017:27017"
  
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: user
          ME_CONFIG_MONGODB_ADMINPASSWORD: 123
          ME_CONFIG_MONGODB_URL: mongodb://user:123@mongo:27017/
          ME_CONFIG_BASICAUTH: false

    backend:
      build: 
          context: ./
      depends_on:
          - mongo
      restart: always
      ports:
          - 8080:8080
      environment:
          DB_PORT: 27017
          DB_HOST: mongo
          DB_USER: user
          DB_PASS: 123
          DB_NAME: fav
          CACHE_HOST: redis
          CACHE_PORT: 6379

    redis:
      image: redis
      ports:
          - "6379:6379"