version: '3.3'

services: 
    mongo:
      image: mongo
      environment: 
        MONGO_INITDB_DATABASE: inspections
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: 123
      ports: 
        - "27017:27017"
  
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: user
          ME_CONFIG_MONGODB_ADMINPASSWORD: 123
          ME_CONFIG_MONGODB_URL: mongodb://user:123@mongo:27017/
          ME_CONFIG_BASICAUTH: false

    redis:
      image: redis
      ports:
          - "6379:6379"